import type { TDSRecordInsert, TDSRecordUpdate, TDSRecordWithRelations, TDSUnitInsert, TDSUnitUpdate } from '@/types/tds.types';
export declare function useTDSRecords(filters?: {
    customerId?: string;
    machineId?: string;
    status?: string;
    dateFrom?: string;
    dateTo?: string;
}): import("@tanstack/react-query").UseQueryResult<TDSRecordWithRelations[], Error>;
export declare function useTDSRecord(id: string | undefined): import("@tanstack/react-query").UseQueryResult<TDSRecordWithRelations | null, Error>;
export declare function useCreateTDS(): import("@tanstack/react-query").UseMutationResult<{
    id: string;
    customer_id: string | null;
    machine_id: string | null;
    date: string;
    order_number: string;
    num_units: number | null;
    job_type: string | null;
    job_product_name: string | null;
    design_artwork_bromide: string | null;
    operator_name: string | null;
    speed_mpm: number | null;
    downtime_min: number | null;
    shift_no: string | null;
    action_on_job: string | null;
    substrate_laminate: string | null;
    surface_type: string | null;
    width_mm: number | null;
    corona_treatment: boolean;
    corona_wattage: number | null;
    corona_treatment_side: string | null;
    corona_dyne_level: number | null;
    foil_supplier: string | null;
    foil_type: string | null;
    foil_colour_finish: string | null;
    tape_test: string | null;
    flow_marks: string | null;
    flex_test: string | null;
    graphite_test: string | null;
    adhesion_test: string | null;
    rub_scuff_test: string | null;
    ink_lay_tone_check: string | null;
    overall_result: string | null;
    quality_notes: string | null;
    status: string;
    prepared_by: string | null;
    prepared_at: string;
    approved_by: string | null;
    approved_at: string | null;
    created_at: string;
    updated_at: string;
}, Error, {
    record: TDSRecordInsert;
    units: TDSUnitInsert[];
}, unknown>;
export declare function useUpdateTDS(): import("@tanstack/react-query").UseMutationResult<TDSRecordWithRelations, Error, {
    id: string;
    updates: TDSRecordUpdate;
    unitUpdates?: TDSUnitUpdate[];
    isAutoSave?: boolean;
}, unknown>;
export declare function useUpdateTDSStatus(): import("@tanstack/react-query").UseMutationResult<{
    id: string;
    customer_id: string | null;
    machine_id: string | null;
    date: string;
    order_number: string;
    num_units: number | null;
    job_type: string | null;
    job_product_name: string | null;
    design_artwork_bromide: string | null;
    operator_name: string | null;
    speed_mpm: number | null;
    downtime_min: number | null;
    shift_no: string | null;
    action_on_job: string | null;
    substrate_laminate: string | null;
    surface_type: string | null;
    width_mm: number | null;
    corona_treatment: boolean;
    corona_wattage: number | null;
    corona_treatment_side: string | null;
    corona_dyne_level: number | null;
    foil_supplier: string | null;
    foil_type: string | null;
    foil_colour_finish: string | null;
    tape_test: string | null;
    flow_marks: string | null;
    flex_test: string | null;
    graphite_test: string | null;
    adhesion_test: string | null;
    rub_scuff_test: string | null;
    ink_lay_tone_check: string | null;
    overall_result: string | null;
    quality_notes: string | null;
    status: string;
    prepared_by: string | null;
    prepared_at: string;
    approved_by: string | null;
    approved_at: string | null;
    created_at: string;
    updated_at: string;
}, Error, {
    id: string;
    status: string;
}, unknown>;
export declare function useDeleteTDS(): import("@tanstack/react-query").UseMutationResult<void, Error, string, unknown>;
export declare function useBatchCodeSuggestions(query: string): import("@tanstack/react-query").UseQueryResult<any[], Error>;
